-- SEASONS
DROP TABLE IF EXISTS NBA.SEASONS;
CREATE TABLE IF NOT EXISTS NBA.SEASONS(
	SEASON varchar(16) NOT NULL,
    SEASON_TYPE varchar(16),
    SEASON_START DATE DEFAULT NULL,
    SEASON_END DATE DEFAULT NULL,
    PRIMARY KEY (SEASON, SEASON_TYPE));
INSERT INTO NBA.SEASONS(
	SEASON,
    SEASON_TYPE,
    SEASON_START,
    SEASON_END) 
		VALUES
			("2020","allstar","2020-02-14","2020-02-16"),
            ("2020","playoffs","2020-08-17","2020-10-11"),
			("2020","preseason","2020-12-11", "2020-12-19"),
            ("2020", "regular","2020-12-22","2021-05-16"),
            ("2021","allstar","2021-03-07","2021-03-09"),
            ("2021","playoffs","2021-05-22","2021-07-20"),
			("2021", "preseason","2021-10-03", "2021-10-15"),
            ("2021","regular","2021-10-19","2022-04-10");

-- TEAMS
DROP TABLE IF EXISTS NBA.TEAMS;
CREATE TABLE NBA.TEAMS AS (
	SELECT DISTINCT TEAM_ID, TEAM_ABBREVIATION FROM NBA.GAME_DETAILS
);

-- PLAYER BASICS
DROP TABLE IF EXISTS NBA.PLAYER_BASICS;
CREATE TABLE NBA.PLAYER_BASICS AS(
	SELECT DISTINCT PLAYER_ID, PLAYER_NAME FROM NBA.GAME_DETAILS);
    
-- GAME_BASICS
DROP TABLE IF EXISTS NBA.GAME_BASICS;
CREATE TABLE NBA.GAME_BASICS AS (
	SELECT 
		DISTINCT GAME_ID, 
        GAME_DATE_EST, 
        GAMES.SEASON, 
        SEASON_TYPE
			FROM (GAMES LEFT JOIN SEASONS 
				ON GAMES.GAME_DATE_EST BETWEEN SEASONS.SEASON_START AND SEASONS.SEASON_END));

-- PLAYER_TEAM_SEASON_STATS
DROP TABLE IF EXISTS NBA.PLAYER_TEAM_SEASON_STATS;
CREATE TABLE PLAYER_TEAM_SEASON_STATS AS (
	SELECT 
		GAME_DETAILS.PLAYER_ID,
        GAME_BASICS.SEASON,
        GAME_BASICS.SEASON_TYPE,
        GAME_DETAILS.TEAM_ID,
        GAME_DETAILS.TEAM_ABBREVIATION,
        ROUND(AVG(COALESCE(GAME_DETAILS.PTS, 0 )),1) AS AVG_SCORE,
        ROUND(AVG(COALESCE(GAME_DETAILS.OREB, 0) + COALESCE(GAME_DETAILS.DREB, 0)),1) AS AVG_REB,
        ROUND(AVG(COALESCE(GAME_DETAILS.AST, 0)),1) AS AVG_ASSIT
			FROM GAME_DETAILS LEFT JOIN GAME_BASICS
				ON GAME_DETAILS.GAME_ID = GAME_BASICS.GAME_ID
					GROUP BY 
						PLAYER_ID,
                        SEASON,
                        SEASON_TYPE,
                        TEAM_ID,
                        TEAM_ABBREVIATION
);